version: 7
application: chaca-tiny-url
service: redirect
runtime: python27
api_version: 1
threadsafe: true

builtins:
- appstats: on

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest

handlers:
- url: /.*
  script: main.app
